CREATE TABLE `balmetal_app`.`PRIVILEGIO`(
	`ID_PRIVILEGIO` INT NOT NULL AUTO_INCREMENT,
	`CODIGO_PRIVILEGIO` VARCHAR(50) NOT NULL,
    PRIMARY KEY (`ID_PRIVILEGIO`)
) ENGINE = MyISAM;

CREATE TABLE `balmetal_app`.`PERFIL`(
    `ID_PERFIL` INT NOT NULL AUTO_INCREMENT,
    `NOMBRE_PERFIL` VARCHAR(30) NULL,
    PRIMARY KEY (`ID_PERFIL`)
) ENGINE = MyISAM;

CREATE TABLE `balmetal_app`.`PERFIL_PRIVILEGIO`(
    `ID_PRIVILEGIO` INT NOT NULL AUTO_INCREMENT,
    `ID_PERFIL` INT NOT NULL,
    PRIMARY KEY (`ID_PRIVILEGIO`,`ID_PERFIL`)
) ENGINE = MyISAM;

CREATE TABLE `balmetal_app`.`USUARIOS` ( 
    `ID_USUARIO` INT NOT NULL AUTO_INCREMENT , 
    `NOMBRE` VARCHAR(256) NOT NULL , 
    `APELLIDO` VARCHAR(100) NOT NULL , 
    `HABILITADO` SMALLINT NOT NULL , 
    `ID_PERFIL` INT NOT NULL , 
    `CORREO_ELECTRONICO` VARCHAR(200) NULL , 
    PRIMARY KEY (`ID_USUARIO`),
    FOREIGN KEY (`ID_PERFIL`) REFERENCES PERFIL(`ID_PERFIL`)
) ENGINE = MyISAM;

CREATE TABLE `balmetal_app`.`REGION`(
    `ID_REGION` INT NOT NULL,
    `NOMBRE_REGION` VARCHAR(30) NOT NULL,
    PRIMARY KEY (`ID_REGION`)
) ENGINE = MyISAM;

CREATE TABLE `balmetal_app`.`PROVEEDOR` ( 
    `ID_PROVEEDOR` INT NOT NULL AUTO_INCREMENT, 
    `CODIGO_PROVEEDOR` VARCHAR(256) NOT NULL,
    `NOMBRE` VARCHAR(100) NOT NULL, 
    `RUT` VARCHAR(100) NULL, 
    `NIF_CIF` VARCHAR(100) NULL, 
    `DIRECCION` VARCHAR(200) NULL, 
    `LOCALIDAD` VARCHAR(200) NULL, 
    `ID_REGION` SMALLINT NULL, 
    `TELEFONO` VARCHAR(20) NULL,
    `CORREO_ELECTRONICO` VARCHAR(100) NULL,
    `DIRECCION_WEB` VARCHAR(200) NULL,
    `HABILITADO` SMALLINT NOT NULL,
    PRIMARY KEY (`ID_PROVEEDOR`),
    FOREIGN KEY (`ID_REGION`) REFERENCES REGION(`ID_REGION`)
) ENGINE = MyISAM;

CREATE TABLE `balmetal_app`.`CLIENTE` ( 
    `ID_CLIENTE` INT NOT NULL AUTO_INCREMENT, 
    `CODIGO_CLIENTE` VARCHAR(256) NOT NULL,
    `NOMBRE` VARCHAR(100) NOT NULL, 
    `RUT` VARCHAR(100) NULL, 
    `NIF_CIF` VARCHAR(100) NULL, 
    `DIRECCION` VARCHAR(200) NULL, 
    `LOCALIDAD` VARCHAR(200) NULL, 
    `ID_REGION` SMALLINT NULL, 
	`CODIGO_POSTAL` INT NULL, 
    `TELEFONO` VARCHAR(20) NULL,
    `CORREO_ELECTRONICO` VARCHAR(100) NULL,
    `DIRECCION_WEB` VARCHAR(200) NULL,
	`FORMA_PAGO` VARCHAR(50) NULL,
	`ENTIDAD_BANCARIA` VARCHAR(50) NULL,
	`CUENTA_BANCARIA` VARCHAR(50) NULL,
    `HABILITADO` SMALLINT NOT NULL,
    PRIMARY KEY (`ID_CLIENTE`),
    FOREIGN KEY (`ID_REGION`) REFERENCES REGION(`ID_REGION`)
) ENGINE = MyISAM;

CREATE TABLE `balmetal_app`.`FAMILIA`(
	`ID_FAMILIA` INT NOT NULL AUTO_INCREMENT,
	`CODIGO_FAMILIA` VARCHAR(50) NOT NULL,
	`NOMBRE_FAMILIA` VARCHAR(50) NOT NULL,
    PRIMARY KEY (`ID_FAMILIA`)
) ENGINE = MyISAM;

CREATE TABLE `balmetal_app`.`MODELO_VEHICULO`(
	`ID_MODELO_VEHICULO` INT NOT NULL AUTO_INCREMENT,
	`CODIGO_MODELO_VEHICULO` VARCHAR(50) NOT NULL,
	`NOMBRE_MODELO_VEHICULO` VARCHAR(50) NOT NULL,
    PRIMARY KEY (`ID_MODELO_VEHICULO`)
) ENGINE = MyISAM;

CREATE TABLE `balmetal_app`.`ARTICULO` ( 
    `ID_ARTICULO` INT NOT NULL AUTO_INCREMENT, 
    `CODIGO_ARTICULO` INT NULL,
	`REFERENCIA` INT NULL,
	`ID_FAMILIA` INT NULL,
    `DESCRIPCION` VARCHAR(200) NULL, 
    `DESCRIPCION_CORTA` VARCHAR(100) NULL, 
    `UBICACION` VARCHAR(100) NULL, 
    `STOCK` INT NULL, 
    `STOCK_MINIMO` INT NULL, 
    `AVISO_MINIMO` BOOLEAN NULL, 
	`DATOS_ARTICULO` VARCHAR(200) NULL, 
    `FECHA_ALTA` DATETIME NULL,
    `EMBALAJE` VARCHAR(200) NULL,
    `UNIDADES_POR_CAJA` INT NULL,
	`PREGUNTAR_PRECIO_TICKET` BOOLEAN NULL,
	`MODIFICAR_DESCRIPCION_TICKET` BOOLEAN NULL,
	`OBSERVACIONES` VARCHAR(200) NULL,
    `PRECIO_COMPRA` INT NULL,
	`PRECIO_INTERNO` INT NULL,
	`PRECIO_VENTA` INT NULL,
	`CODIGO_BARRAS` VARCHAR(100) NULL,
    PRIMARY KEY (`ID_ARTICULO`),
    FOREIGN KEY (`ID_FAMILIA`) REFERENCES REGION(`ID_FAMILIA`)
) ENGINE = MyISAM;

CREATE TABLE `balmetal_app`.`PROVEEDOR_ARTICULO`(
    `ID_PROVEEDOR` INT NOT NULL AUTO_INCREMENT,
    `ID_ARTICULO` INT NOT NULL,
    PRIMARY KEY (`ID_PROVEEDOR`,`ID_ARTICULO`)
) ENGINE = MyISAM;